import Layout from '@/components/layout'
import Head from 'next/head'
import React from 'react'
import localFont from 'next/font/local'
const myFont = localFont({ src: './Avenir-Regular.woff2' })
import { RxInstagramLogo, RxLinkedinLogo, RxEnvelopeClosed } from "react-icons/rx";
import { AiOutlineMedium, AiOutlineGithub } from "react-icons/ai";
import Link from 'next/link'
// import MainContent from '@/components/mainContent'
import dynamic from 'next/dynamic'
const MainContent = dynamic(() => import('../components/mainContent'))
const Home = () => {
  return (
    <>
      <Layout title='Home | Rakha Randhikatama'>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <main className='mb-[300px] '>
          <div className='flex flex-col justify-center  items-center'>
            <div className='name flex justify-center items-center mt-[74px] text-[58px] leading-[75px'>
              <h1>Rakha
                <br /> Randhikatama
              </h1>
            </div>
            <div className='short-brief w-[338px] flex justify-center mt-11 mb-[66px]'>
              <p className={`${myFont.className} text-[13px] leading-[26px] text-center italic`}>
                Hello there 👋 <br />
                I am a Full-stack web developer <br />
                currently focusing on the front-end development, <br />
                amateur photographer and a stargazer <br />
                I have no prior experience, but I look forward to working with you soon!
              </p>
            </div>
            <div className='social-media flex gap-x-9'>
              <div>
                <Link href="https://www.instagram.com/rakharan/" target="_blank">
                  <RxInstagramLogo />
                </Link>
              </div>
              <div>
                <Link href="https://www.linkedin.com/in/rakha-randhikatama/" target="_blank">
                  <RxLinkedinLogo />
                </Link>
              </div>
              <div>
                <Link href="mailto:randhikatamar@gmail.com" target="_blank">
                  <RxEnvelopeClosed />
                </Link>
              </div>
              <div>
                <Link href="https://medium.com/@randhikatamar" target="_blank">
                  <AiOutlineMedium />
                </Link>
              </div>
              <div>
                <Link href="https://github.com/rakharan" target="_blank">
                  <AiOutlineGithub />
                </Link>
              </div>
            </div>
          </div>
        </main>
        <MainContent />
      </Layout>
    </>
  )
}

export default Home